<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260904132744 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, game_id INT DEFAULT NULL, borrower_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_27BA704BE48FD905 ON history (game_id)');
        $this->addSql('CREATE INDEX IDX_27BA704B11CE312B ON history (borrower_id)');
        $this->addSql('ALTER TABLE history ADD CONSTRAINT FK_27BA704BE48FD905 FOREIGN KEY (game_id) REFERENCES game (id)');
        $this->addSql('ALTER TABLE history ADD CONSTRAINT FK_27BA704B11CE312B FOREIGN KEY (borrower_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE history DROP CONSTRAINT FK_27BA704BE48FD905');
        $this->addSql('ALTER TABLE history DROP CONSTRAINT FK_27BA704B11CE312B');
        $this->addSql('DROP TABLE history');
    }
}
