<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260904143737 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // 1. Supprimer les foreign keys d'abord
        $this->addSql('ALTER TABLE game DROP CONSTRAINT fk_232b318c11ce312b');
        $this->addSql('ALTER TABLE history DROP CONSTRAINT fk_27ba704b11ce312b');
        
        // 2. Supprimer l'index
        $this->addSql('DROP INDEX IF EXISTS UNIQ_IDENTIFIER_EMAIL');
        
        // 3. Supprimer l'ancienne table
        $this->addSql('DROP TABLE IF EXISTS "user"');
        
        // 4. Créer la nouvelle table avec le nouvel index
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON users (email)');
        
        // 5. Recréer les foreign keys vers la nouvelle table
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C11CE312B FOREIGN KEY (borrower_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE history ADD CONSTRAINT FK_27BA704B11CE312B FOREIGN KEY (borrower_id) REFERENCES users (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX IF EXISTS UNIQ_IDENTIFIER_EMAIL');
        $this->addSql('DROP TABLE users');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email)');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C11CE312B');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT fk_232b318c11ce312b FOREIGN KEY (borrower_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE history DROP CONSTRAINT FK_27BA704B11CE312B');
        $this->addSql('ALTER TABLE history ADD CONSTRAINT fk_27ba704b11ce312b FOREIGN KEY (borrower_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
